### ISSUE TITLE
Unragdolling not responding to animations

### ISSUE THREAD

**Issue by ImAvafe** [LeoStormer/ragdoll-system#2]
Currently if I ragdoll, press a key to walk, and then unragdoll, the walking animation will not play until I restart the walk cycle.

https://github.com/LeoStormer/ragdoll-system/assets/65048459/0b772cbe-d2a5-4b09-9618-bf47ed52db45

**Comment by LeoStormer** [comment]
Hello, I'm unable to reproduce this bug. Are you experiencing this on the latest version of the system, version 0.3.0? If so can you send a small example that reproduces this bug?

**Comment by ImAvafe** [comment]
Here's a Roblox place file with the bug being produced. My sample code is in StarterPlayerScripts.

[RagdollSystemBug.zip](https://github.com/LeoStormer/ragdoll-system/files/12316027/RagdollSystemBug.zip)
